from database_handler import DatabaseHandler

if __name__ == "__main__":
    db_handler = DatabaseHandler('db_credentials.json')
    db_handler.execute_sql_script('sql_scripts/create_foodbanks_table.sql')
    print("created foodbanks tables")
    db_handler.fetch_and_insert("data_via_direct_download/foodbanks/", True, 'sql_scripts/insert_foodbanks_table.sql')
    print("inserted into foodbanks table")
    db_handler.execute_sql_script('sql_scripts/calculate_distances.sql')
    print("calculated distances")
    db_handler.execute_sql_script('sql_scripts/create_needs_table.sql')
    print("created needs table")
    db_handler.fetch_and_insert("data_via_direct_download/needs/", False, 'sql_scripts/insert_needs_table.sql')
    print("inserted into needs table")
    db_handler.execute_sql_script('sql_scripts/alter_needs_table.sql')
    print("altered needs table")
    db_handler.execute_sql_script('sql_scripts/create_foodneedsexcess_table.sql')
    print("created foodneeds and foodexcess tables")
    db_handler.execute_sql_script('sql_scripts/insert_foodneedsexcess_table.sql')
    print("inserted into foodneeds and foodexcess tables")
    db_handler.execute_sql_script('sql_scripts/create_insert_foodbank_item_matches.sql')
    print("created and inserted into foodbank item matches table")
    #db_handler.execute_sql_script('sql_scripts/sql_scripts/delete_unwanted_tables.sql')
    #print("Deleted all unwanted tables.")
