DROP TABLE IF EXISTS foodneed CASCADE;
DROP TABLE IF EXISTS foodexcess CASCADE;
DROP TABLE IF EXISTS foodbanks_distances CASCADE;
DROP TABLE IF EXISTS foodbanks_locations CASCADE;
DROP TABLE IF EXISTS foodbank CASCADE;
